FROM golang:1.23 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/winsim ./cmd/winsim

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/winsim /usr/local/bin/winsim
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/winsim"]
