// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: pkg/proto/indexer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IndexerService_IngestEvents_FullMethodName = "/indexer.IndexerService/IngestEvents"
	IndexerService_IngestAlerts_FullMethodName = "/indexer.IndexerService/IngestAlerts"
	IndexerService_Health_FullMethodName       = "/indexer.IndexerService/Health"
)

// IndexerServiceClient is the client API for IndexerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndexerServiceClient interface {
	IngestEvents(ctx context.Context, opts ...grpc.CallOption) (IndexerService_IngestEventsClient, error)
	IngestAlerts(ctx context.Context, opts ...grpc.CallOption) (IndexerService_IngestAlertsClient, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type indexerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexerServiceClient(cc grpc.ClientConnInterface) IndexerServiceClient {
	return &indexerServiceClient{cc}
}

func (c *indexerServiceClient) IngestEvents(ctx context.Context, opts ...grpc.CallOption) (IndexerService_IngestEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &IndexerService_ServiceDesc.Streams[0], IndexerService_IngestEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &indexerServiceIngestEventsClient{stream}
	return x, nil
}

type IndexerService_IngestEventsClient interface {
	Send(*EventBatch) error
	CloseAndRecv() (*IngestResponse, error)
	grpc.ClientStream
}

type indexerServiceIngestEventsClient struct {
	grpc.ClientStream
}

func (x *indexerServiceIngestEventsClient) Send(m *EventBatch) error {
	return x.ClientStream.SendMsg(m)
}

func (x *indexerServiceIngestEventsClient) CloseAndRecv() (*IngestResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(IngestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *indexerServiceClient) IngestAlerts(ctx context.Context, opts ...grpc.CallOption) (IndexerService_IngestAlertsClient, error) {
	stream, err := c.cc.NewStream(ctx, &IndexerService_ServiceDesc.Streams[1], IndexerService_IngestAlerts_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &indexerServiceIngestAlertsClient{stream}
	return x, nil
}

type IndexerService_IngestAlertsClient interface {
	Send(*AlertBatch) error
	CloseAndRecv() (*IngestResponse, error)
	grpc.ClientStream
}

type indexerServiceIngestAlertsClient struct {
	grpc.ClientStream
}

func (x *indexerServiceIngestAlertsClient) Send(m *AlertBatch) error {
	return x.ClientStream.SendMsg(m)
}

func (x *indexerServiceIngestAlertsClient) CloseAndRecv() (*IngestResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(IngestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *indexerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, IndexerService_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexerServiceServer is the server API for IndexerService service.
// All implementations must embed UnimplementedIndexerServiceServer
// for forward compatibility
type IndexerServiceServer interface {
	IngestEvents(IndexerService_IngestEventsServer) error
	IngestAlerts(IndexerService_IngestAlertsServer) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedIndexerServiceServer()
}

// UnimplementedIndexerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIndexerServiceServer struct {
}

func (UnimplementedIndexerServiceServer) IngestEvents(IndexerService_IngestEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method IngestEvents not implemented")
}
func (UnimplementedIndexerServiceServer) IngestAlerts(IndexerService_IngestAlertsServer) error {
	return status.Errorf(codes.Unimplemented, "method IngestAlerts not implemented")
}
func (UnimplementedIndexerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedIndexerServiceServer) mustEmbedUnimplementedIndexerServiceServer() {}

// UnsafeIndexerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexerServiceServer will
// result in compilation errors.
type UnsafeIndexerServiceServer interface {
	mustEmbedUnimplementedIndexerServiceServer()
}

func RegisterIndexerServiceServer(s grpc.ServiceRegistrar, srv IndexerServiceServer) {
	s.RegisterService(&IndexerService_ServiceDesc, srv)
}

func _IndexerService_IngestEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IndexerServiceServer).IngestEvents(&indexerServiceIngestEventsServer{stream})
}

type IndexerService_IngestEventsServer interface {
	SendAndClose(*IngestResponse) error
	Recv() (*EventBatch, error)
	grpc.ServerStream
}

type indexerServiceIngestEventsServer struct {
	grpc.ServerStream
}

func (x *indexerServiceIngestEventsServer) SendAndClose(m *IngestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *indexerServiceIngestEventsServer) Recv() (*EventBatch, error) {
	m := new(EventBatch)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _IndexerService_IngestAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IndexerServiceServer).IngestAlerts(&indexerServiceIngestAlertsServer{stream})
}

type IndexerService_IngestAlertsServer interface {
	SendAndClose(*IngestResponse) error
	Recv() (*AlertBatch, error)
	grpc.ServerStream
}

type indexerServiceIngestAlertsServer struct {
	grpc.ServerStream
}

func (x *indexerServiceIngestAlertsServer) SendAndClose(m *IngestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *indexerServiceIngestAlertsServer) Recv() (*AlertBatch, error) {
	m := new(AlertBatch)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _IndexerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndexerService_ServiceDesc is the grpc.ServiceDesc for IndexerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "indexer.IndexerService",
	HandlerType: (*IndexerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _IndexerService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestEvents",
			Handler:       _IndexerService_IngestEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "IngestAlerts",
			Handler:       _IndexerService_IngestAlerts_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/indexer.proto",
}
